version: '3.3'

services:
  dwi-backend:
    image: zoncord.azurecr.io/dwi-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn dwi_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/dwi_backend/staticfiles
      - media_volume:/home/dwi_backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - zoncorddeploy_static_media_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  zoncorddeploy_static_media_network:
    external: true