version: '3.3'

services:
  dwi-backend:
    image: zoncord.azurecr.io/dwi-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn dwi_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - zoncorddeploy_static_volume:/home/staticfiles/ZoncordBackend
      - zoncorddeploy_media_volume:/home/mediafiles/ZoncordBackend
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - zoncorddeploy_static_media_network

volumes:
  zoncorddeploy_static_volume:
    external: true
  zoncorddeploy_media_volume:
    external: true

networks:
  zoncorddeploy_static_media_network:
    external: true