# Generated by Django 3.2.13 on 2022-05-28 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.CharField(max_length=4096, verbose_name='description')),
                ('date_time_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time of creation')),
                ('date_time_of_last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Date and time of last edit')),
                ('is_private', models.BooleanField(default=False, verbose_name='privacy')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.CharField(max_length=4096, verbose_name='description')),
                ('date_time_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time of creation')),
                ('date_time_of_last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Date and time of last edit')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.CharField(max_length=4096, verbose_name='description')),
                ('date_time_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time of creation')),
                ('date_time_of_last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Date and time of last edit')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of incident')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='achievements.achievement', verbose_name='achievement')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='achievements.category', verbose_name='category'),
        ),
    ]
