# Generated by Django 3.2.13 on 2022-07-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='likes',
        ),
    ]
