# Generated by Django 3.2.13 on 2022-04-26 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_incident_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 18, 37, 38, 800440), verbose_name='Date and time of incident'),
        ),
    ]
