# Generated by Django 3.2.13 on 2022-05-03 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_alter_incident_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 10, 46, 28, 224707), verbose_name='Date and time of incident'),
        ),
    ]
