# Generated by Django 3.2.13 on 2022-05-03 10:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0008_alter_incident_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='owners',
            field=models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='achievement creators'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 10, 47, 55, 358425), verbose_name='Date and time of incident'),
        ),
    ]
