# Generated by Django 3.2.13 on 2022-07-15 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of creation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_time_of_last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of last edit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of creation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_of_last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of last edit'),
        ),
    ]
