# Generated by Django 3.2.13 on 2022-07-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_delete_answerrating'),
        ('blog', '0004_auto_20220715_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.comment', verbose_name='comment'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
